controller_manager:
  ros__parameters:
    update_rate: 100

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_01_joint
      - arm_02_joint
      - arm_03_joint
      - arm_04_joint
      - arm_tools_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity